1. numpy
2. pandas
3. 머신러닝(신경망x)
4. 딥러닝(신경망)
  
gole : 딥러닝의 코드 이해. 적용할수 있다.

# numpy
- 산술연산을 위한 패키지
    - ndarray (다차원 배열) 배열 연산 + 브로드캐스팅 기능을 이용해 연산 가능하게 해준다.
    - 장점 : 반복문을 작성할 필요가 없다.
    - 선형대수, 난수 생성
- numpy 산술데이터 처리만 가능한 라이브러리, pandas 통계 분석 처리를 위한 라이브러리

In [9]:
import numpy as np

In [10]:
my_arr = np.arange(1000)

In [11]:
my_arr?

In [7]:
my_list_1 = [i for i in range(1000)]

In [12]:
my_list_1?

- 리스트 : 객체 저장소

In [35]:
list_2 = [print, range]

In [36]:
list_2 * 2

[<function print>, range, <function print>, range]

In [37]:
list_2[0]("hello world")

hello world

In [38]:
list_2[1](10)

range(0, 10)

In [39]:
type(my_list_1)

list

In [40]:
my_array_1 = np.array(my_list_1)

In [41]:
my_array_1 *2

array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58,   60,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  212,  214,  216,  218,
        220,  222,  224,  226,  228,  230,  232,  234,  236,  238,  240,
        242,  244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
        264,  266,  268,  270,  272,  274,  276,  278,  280,  282,  284,
        286,  288,  290,  292,  294,  296,  298,  300,  302,  304,  306,
        308,  310,  312,  314,  316,  318,  320,  322,  324,  326,  328,
        330,  332,  334,  336,  338,  340,  342,  344,  346,  348,  350,
        352,  354,  356,  358,  360,  362,  364,  366,  368,  370,  372,
        374,  376,  378,  380,  382,  384,  386,  388,  390,  392,  394,
        396,  398,  400,  402,  404,  406,  408,  410,  412,  414,  416,
        418,  420,  422,  424,  426,  428,  430,  432,  434,  436,  438,
        440,  442,  444,  446,  448,  450,  452,  454,  456,  458,  460,
        462,  464,  466,  468,  470,  472,  474,  476,  478,  480,  482,
        484,  486,  488,  490,  492,  494,  496,  498,  500,  502,  504,
        506,  508,  510,  512,  514,  516,  518,  520,  522,  524,  526,
        528,  530,  532,  534,  536,  538,  540,  542,  544,  546,  548,
        550,  552,  554,  556,  558,  560,  562,  564,  566,  568,  570,
        572,  574,  576,  578,  580,  582,  584,  586,  588,  590,  592,
        594,  596,  598,  600,  602,  604,  606,  608,  610,  612,  614,
        616,  618,  620,  622,  624,  626,  628,  630,  632,  634,  636,
        638,  640,  642,  644,  646,  648,  650,  652,  654,  656,  658,
        660,  662,  664,  666,  668,  670,  672,  674,  676,  678,  680,
        682,  684,  686,  688,  690,  692,  694,  696,  698,  700,  702,
        704,  706,  708,  710,  712,  714,  716,  718,  720,  722,  724,
        726,  728,  730,  732,  734,  736,  738,  740,  742,  744,  746,
        748,  750,  752,  754,  756,  758,  760,  762,  764,  766,  768,
        770,  772,  774,  776,  778,  780,  782,  784,  786,  788,  790,
        792,  794,  796,  798,  800,  802,  804,  806,  808,  810,  812,
        814,  816,  818,  820,  822,  824,  826,  828,  830,  832,  834,
        836,  838,  840,  842,  844,  846,  848,  850,  852,  854,  856,
        858,  860,  862,  864,  866,  868,  870,  872,  874,  876,  878,
        880,  882,  884,  886,  888,  890,  892,  894,  896,  898,  900,
        902,  904,  906,  908,  910,  912,  914,  916,  918,  920,  922,
        924,  926,  928,  930,  932,  934,  936,  938,  940,  942,  944,
        946,  948,  950,  952,  954,  956,  958,  960,  962,  964,  966,
        968,  970,  972,  974,  976,  978,  980,  982,  984,  986,  988,
        990,  992,  994,  996,  998, 1000, 1002, 1004, 1006, 1008, 1010,
       1012, 1014, 1016, 1018, 1020, 1022, 1024, 1026, 1028, 1030, 1032,
       1034, 1036, 1038, 1040, 1042, 1044, 1046, 1048, 1050, 1052, 1054,
       1056, 1058, 1060, 1062, 1064, 1066, 1068, 1070, 1072, 1074, 1076,
       1078, 1080, 1082, 1084, 1086, 1088, 1090, 1092, 1094, 1096, 1098,
       1100, 1102, 1104, 1106, 1108, 1110, 1112, 1114, 1116, 1118, 1120,
       1122, 1124, 1126, 1128, 1130, 1132, 1134, 1136, 1138, 1140, 1142,
       1144, 1146, 1148, 1150, 1152, 1154, 1156, 1158, 1160, 1162, 1164,
       1166, 1168, 1170, 1172, 1174, 1176, 1178, 1180, 1182, 1184, 1186,
       1188, 1190, 1192, 1194, 1196, 1198, 1200, 1202, 1204, 1206, 1208,
       1210, 1212, 1214, 1216, 1218, 1220, 1222, 1224, 1226, 1228, 1230,
       1232, 1234, 1236, 1238, 1240, 1242, 1244, 1246, 1248, 1250, 1252,
       1254, 1256, 1258, 1260, 1262, 1264, 1266, 1268, 1270, 1272, 1274,
       1276, 1278, 1280, 1282, 1284, 1286, 1288, 1290, 1292, 1294, 1296,
       1298, 1300, 1302, 1304, 1306, 1308, 1310, 1312, 1314, 1316, 1318,
       1320, 1322, 1324, 1326, 1328, 1330, 1332, 1334, 1336, 1338, 1340,
       1342, 1344, 1346, 1348, 1350, 1352, 1354, 1356, 1358, 1360, 1362,
       1364, 1366, 1368, 1370, 1372, 1374, 1376, 1378, 1380, 1382, 1384,
       1386, 1388, 1390, 1392, 1394, 1396, 1398, 1400, 1402, 1404, 1406,
       1408, 1410, 1412, 1414, 1416, 1418, 1420, 1422, 1424, 1426, 1428,
       1430, 1432, 1434, 1436, 1438, 1440, 1442, 1444, 1446, 1448, 1450,
       1452, 1454, 1456, 1458, 1460, 1462, 1464, 1466, 1468, 1470, 1472,
       1474, 1476, 1478, 1480, 1482, 1484, 1486, 1488, 1490, 1492, 1494,
       1496, 1498, 1500, 1502, 1504, 1506, 1508, 1510, 1512, 1514, 1516,
       1518, 1520, 1522, 1524, 1526, 1528, 1530, 1532, 1534, 1536, 1538,
       1540, 1542, 1544, 1546, 1548, 1550, 1552, 1554, 1556, 1558, 1560,
       1562, 1564, 1566, 1568, 1570, 1572, 1574, 1576, 1578, 1580, 1582,
       1584, 1586, 1588, 1590, 1592, 1594, 1596, 1598, 1600, 1602, 1604,
       1606, 1608, 1610, 1612, 1614, 1616, 1618, 1620, 1622, 1624, 1626,
       1628, 1630, 1632, 1634, 1636, 1638, 1640, 1642, 1644, 1646, 1648,
       1650, 1652, 1654, 1656, 1658, 1660, 1662, 1664, 1666, 1668, 1670,
       1672, 1674, 1676, 1678, 1680, 1682, 1684, 1686, 1688, 1690, 1692,
       1694, 1696, 1698, 1700, 1702, 1704, 1706, 1708, 1710, 1712, 1714,
       1716, 1718, 1720, 1722, 1724, 1726, 1728, 1730, 1732, 1734, 1736,
       1738, 1740, 1742, 1744, 1746, 1748, 1750, 1752, 1754, 1756, 1758,
       1760, 1762, 1764, 1766, 1768, 1770, 1772, 1774, 1776, 1778, 1780,
       1782, 1784, 1786, 1788, 1790, 1792, 1794, 1796, 1798, 1800, 1802,
       1804, 1806, 1808, 1810, 1812, 1814, 1816, 1818, 1820, 1822, 1824,
       1826, 1828, 1830, 1832, 1834, 1836, 1838, 1840, 1842, 1844, 1846,
       1848, 1850, 1852, 1854, 1856, 1858, 1860, 1862, 1864, 1866, 1868,
       1870, 1872, 1874, 1876, 1878, 1880, 1882, 1884, 1886, 1888, 1890,
       1892, 1894, 1896, 1898, 1900, 1902, 1904, 1906, 1908, 1910, 1912,
       1914, 1916, 1918, 1920, 1922, 1924, 1926, 1928, 1930, 1932, 1934,
       1936, 1938, 1940, 1942, 1944, 1946, 1948, 1950, 1952, 1954, 1956,
       1958, 1960, 1962, 1964, 1966, 1968, 1970, 1972, 1974, 1976, 1978,
       1980, 1982, 1984, 1986, 1988, 1990, 1992, 1994, 1996, 1998])

In [42]:
my_arr2=np.array(list_2)

In [43]:
my_arr2[0]("hello world")

hello world

In [44]:
type(my_arr2)

numpy.ndarray

In [45]:
my_list_1 * 2

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

In [46]:
my_arr = np.arange(100000)

In [47]:
%time for _ in range(10):my_arr2 = my_arr*2

Wall time: 1e+03 µs

In [48]:
my_arr2

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [49]:
my_list = list(my_arr)

In [50]:
%time for _ in range(10):my_list2 = [i*2 for i in my_list ]

Wall time: 398 ms

Numpy ndarray : 다차원 배열 객체
- numpy 는 ndarray라고 하는 N차원 배열 객체 사용

In [51]:
data = np.random.randn(2,3)

In [52]:
data

array([[ 0.92230624, -1.51439758,  1.58033582],
       [-0.34252766, -1.10818752, -0.57169977]])

In [53]:
data.shape

(2, 3)

In [54]:
data *10

array([[  9.22306243, -15.14397585,  15.80335821],
       [ -3.42527657, -11.08187518,  -5.71699768]])

In [55]:
data + data

array([[ 1.84461249, -3.02879517,  3.16067164],
       [-0.68505531, -2.21637504, -1.14339954]])

# ndarray 생성

In [56]:
data1 = np.random.randn(3,3)

In [57]:
data2 = np.random.randn(2,3)

In [58]:
data1 + data2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3)

In [59]:
data1 = [6,5,7,1,8]

In [60]:
type(data1)

list

In [61]:
arr1 = np.array(data1)

In [62]:
type(arr1)

numpy.ndarray

In [63]:
arr1.shape

(5,)

In [64]:
data2 = [[1,2,3,4],[2,3,4,5]]

In [65]:
arr2 = np.array(data2)

In [66]:
type(arr2)

numpy.ndarray

In [67]:
arr2.shape

(2, 4)

In [68]:
arr2.ndim

2

In [69]:
arr1.ndim

1

In [70]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]]]).ndim

3

# ndarray 생성하기

In [71]:
np.zeros(10) # 메모리를 초기화 하고 0으로 값을 채워 넣는다.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.empty(10) # zeros 비슷하지만, 메모리를 초기화 하지 않고 메모리값을 반환한다.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
np.empty(30)

array([1.06823549e-311, 9.58487353e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.16097020e-028, 1.48339293e-076, 1.48308606e-071,
       6.01033460e-067, 5.01163173e+217, 8.37170074e-144, 8.37821492e+169,
       4.99028117e+174, 7.11938412e-091, 1.59853677e+160, 5.01163188e+217,
       5.49419094e-143, 9.80058441e+252, 7.50189709e+247, 1.35617292e+248,
       4.49831115e-037, 1.29130412e+160, 4.04186736e-037, 2.67452389e+184,
       5.15059328e-062, 5.04621361e+180, 8.37170571e-144, 9.30350598e+199,
       5.60230216e-067, 5.90411176e+294])

In [20]:
np.ones((3,4)) #메모리를 초기화 하고 1로 채워 넣는다.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [25]:
# ndarray 는 권장사항 아님
np.ndarray((3,))

array([1.33511018e-306, 1.33511969e-306, 6.23037996e-307])

# https://c11.kr/myoh-20100701

In [28]:
type(np.ones((3,4))[0][0])

numpy.float64

In [82]:
type(np.full((3,4),10)[0][0])

numpy.int32

In [85]:
type(4/2)

float

In [30]:
4*2.5

int

# index, slice
- 리스트와 동일
- 시퀀셜(Sequential) 데이터 이기 때문에 인덱싱과 슬라이싱이 가능하다.

In [90]:
arr_1 = np.arange(10)

In [92]:
arr_1[5]

5

In [95]:
arr_1[0]

0

In [96]:
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
arr_1[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [97]:
arr_1[0] = 10

In [98]:
arr_1

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [99]:
arr_1[5:-1] = 0

In [100]:
arr_1

array([10,  1,  2,  3,  4,  0,  0,  0,  0,  9])

In [101]:
arr2d_1= np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [105]:
arr2d_1[2]

array([7, 8, 9])

In [106]:
arr2d_1[2][2]

9

In [112]:
arr2d_1[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
arr2d_1[:][1]

array([4, 5, 6])

In [117]:
arr2d_1[:,1]

array([2, 5, 8])

In [121]:
arr2d_2 = np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]]
])

In [122]:
arr2d_2.shape

(2, 3, 4)

In [123]:
arr2d_2[:,[1],[2]]

array([[ 7],
       [19]])

# 블리언 값

In [124]:
names = np.array(["오민엽", "조상우","오정석","정세영"])

In [125]:
names == '오민엽'

array([ True, False, False, False])

In [126]:
names != '오민엽'

array([False,  True,  True,  True])

In [127]:
names[names != '오민엽']

array(['조상우', '오정석', '정세영'], dtype='<U3')

In [128]:
data = np.random.randn(7,4)

In [129]:
data

array([[-0.86464617, -0.97687429,  0.4677455 , -1.11710622],
       [-1.05152894, -0.7337487 ,  0.12119663, -0.27564863],
       [ 0.24661762,  0.75266912,  0.41781214,  0.57523455],
       [ 1.01347698,  1.20123116,  0.27038419, -0.35396996],
       [-0.48653135, -0.04852031,  0.2872791 ,  0.40947229],
       [ 0.60802533,  0.24272869, -0.98671734,  0.53159843],
       [-1.36248835,  1.61764345,  2.38541021, -0.27471576]])

In [130]:
data<0

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True, False, False],
       [False, False,  True, False],
       [ True, False, False,  True]])

In [131]:
data[data<0]

array([-0.86464617, -0.97687429, -1.11710622, -1.05152894, -0.7337487 ,
       -0.27564863, -0.35396996, -0.48653135, -0.04852031, -0.98671734,
       -1.36248835, -0.27471576])

In [132]:
data[data>0]

array([0.4677455 , 0.12119663, 0.24661762, 0.75266912, 0.41781214,
       0.57523455, 1.01347698, 1.20123116, 0.27038419, 0.2872791 ,
       0.40947229, 0.60802533, 0.24272869, 0.53159843, 1.61764345,
       2.38541021])

In [133]:
data[data<0] = -1

In [139]:
data

array([[-1.        , -1.        ,  0.4677455 , -1.        ],
       [-1.        , -1.        ,  0.12119663, -1.        ],
       [ 0.24661762,  0.75266912,  0.41781214,  0.57523455],
       [ 1.01347698,  1.20123116,  0.27038419, -1.        ],
       [-1.        , -1.        ,  0.2872791 ,  0.40947229],
       [ 0.60802533,  0.24272869, -1.        ,  0.53159843],
       [-1.        ,  1.61764345,  2.38541021, -1.        ]])

# 팬시 색인
- 정수 배열 색인

In [141]:
arr = np.empty((8,4))

In [143]:
for i in range(8):
    arr[i] = i

In [145]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

- 특정한 row(행)

In [147]:
arr[[4,3,0]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.]])

In [149]:
arr[[-1,-2,-3]]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [5., 5., 5., 5.]])

In [160]:
arr2 = np.arange(32).reshape((8,4))

In [161]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [165]:
arr2[[1,0],[0,2]]

array([4, 2])

In [174]:
arr2[[1,0]][:]# : 를 내부에 넣는건 x

array([[4, 5, 6, 7],
       [0, 1, 2, 3]])

In [135]:
arr2d_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
arr2d_1[[0,1,2],[1,2,2]]

array([2, 6, 9])

# 벡터화 연산
- 배열에 함수를 적용하고 싶다.
- 함수를 벡터화 시킨다. -> 적용시킨다. (for 문을 구현 성능이 안좋다.)
- 브로드 캐스팅을 이용해 연산한다.

In [175]:
mat_1 = np.array(range(1,10)).reshape(3,3)

In [176]:
mat_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
add_20  = lambda i: i + 20

In [178]:
vec_add_20 = np.vectorize(add_20)

In [179]:
vec_add_20(mat_1)

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [180]:
mat_1 + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

# 전치
    - 행렬의 행과 열을 변경해 준다.

In [185]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [184]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [186]:
arr.transpose()

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [187]:
np.array([1,2,3,4,5]).T

array([1, 2, 3, 4, 5])

In [188]:
np.array([[1,2,3,4,5]]).T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [190]:
vol2=np.array(range(30)).reshape((2,3,5))

In [191]:
vol2.T

array([[[ 0, 15],
        [ 5, 20],
        [10, 25]],

       [[ 1, 16],
        [ 6, 21],
        [11, 26]],

       [[ 2, 17],
        [ 7, 22],
        [12, 27]],

       [[ 3, 18],
        [ 8, 23],
        [13, 28]],

       [[ 4, 19],
        [ 9, 24],
        [14, 29]]])

- 행렬 덧셈,뺄,곱
- 전치행렬
- 방정식 -> 행렬 변경

# 유니버설 함수
- 데이터 원소별로 연산을 수행
    - 단항 유니버설 : exp, sqrt
    - 이항 : maxi, mini, add

In [195]:
arr = np.array([1,4,9,16])

In [196]:
np.sqrt(arr)

array([1., 2., 3., 4.])

In [197]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [34]:
x = np.random.rand(8)
x

array([0.02391   , 0.17122905, 0.02791688, 0.19127988, 0.51568934,
       0.06029349, 0.29430553, 0.46831215])

In [35]:
y= np.random.rand(8)
y

array([0.80265415, 0.75091168, 0.72222606, 0.42088599, 0.57201643,
       0.13325963, 0.38449153, 0.20272113])

In [36]:
z= np.random.rand(8)

In [38]:
np.maximum(x,y)

array([0.80265415, 0.75091168, 0.72222606, 0.42088599, 0.57201643,
       0.13325963, 0.38449153, 0.46831215])

In [215]:
z

array([0.68248166, 0.07706489, 0.08230257, 0.26609981, 0.18606085,
       0.25744735, 0.46881679, 0.35076503])

In [214]:
np.minimum(x,y,z)

array([0.68248166, 0.07706489, 0.08230257, 0.26609981, 0.18606085,
       0.25744735, 0.46881679, 0.35076503])

In [209]:
np.add(x,y)

array([1.5170779 , 0.80448662, 0.37085352, 0.77041216, 0.82216519,
       1.02642691, 1.0924952 , 1.28568459])

In [210]:
x+y

array([1.5170779 , 0.80448662, 0.37085352, 0.77041216, 0.82216519,
       1.02642691, 1.0924952 , 1.28568459])

In [216]:
np.minimum(x,y,arr)

UFuncTypeError: Cannot cast ufunc 'minimum' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [219]:
f = np.random.rand(10)

In [220]:
np.maximum(x,y,f)

ValueError: operands could not be broadcast together with shapes (8,) (8,) (10,)

- 메서드
    - 합, 평균, 표준편차
    - sum
    - mean
    - std,var
    - min, max

In [234]:
arr= np.random.rand(10)

In [235]:
arr

array([0.93846671, 0.00669761, 0.36139371, 0.70142202, 0.70941725,
       0.38658425, 0.06846981, 0.68083499, 0.52414925, 0.39766584])

In [236]:
arr.mean()

0.47751014489299576

In [237]:
np.mean(arr)

0.47751014489299576

In [239]:
np.sum(arr)

4.7751014489299575

In [241]:
arr.sum()

4.7751014489299575

In [250]:
arr= np.random.rand(10,5)

In [245]:
arr.sum()

24.504294686473727

In [247]:
arr

array([[0.75733194, 0.55961268, 0.79900256, 0.88360446, 0.33999292],
       [0.15358012, 0.21960043, 0.35724695, 0.03067401, 0.39430255],
       [0.10576078, 0.32645364, 0.08000438, 0.6859718 , 0.76746577],
       [0.7944953 , 0.83885022, 0.46228515, 0.88375547, 0.58463471],
       [0.58301622, 0.26339298, 0.49403731, 0.71785472, 0.11280676],
       [0.62846892, 0.35904245, 0.41405241, 0.25894341, 0.60692746],
       [0.51492093, 0.36030217, 0.52179099, 0.84946737, 0.60056631],
       [0.17123647, 0.64442687, 0.80559046, 0.48933369, 0.98407237],
       [0.37255846, 0.07297395, 0.72829745, 0.7235362 , 0.05270321],
       [0.29840805, 0.27304816, 0.65485022, 0.55930935, 0.36373353]])

In [246]:
arr.sum(axis=0)

array([4.37977718, 3.91770354, 5.31715788, 6.08245048, 4.8072056 ])

In [248]:
arr.sum(axis=1)

array([3.33954457, 1.15540405, 1.96565636, 3.56402085, 2.17110799,
       2.26743465, 2.84704777, 3.09465986, 1.95006928, 2.14934931])

In [252]:
np.sort(arr) # arr.sort()

array([[0.01560365, 0.07506817, 0.11387828, 0.51985965, 0.58349647],
       [0.1556045 , 0.44617325, 0.5226492 , 0.61241768, 0.62409766],
       [0.13067547, 0.15675434, 0.2651447 , 0.90504796, 0.9109415 ],
       [0.57277762, 0.58362821, 0.59349372, 0.70207736, 0.94950208],
       [0.37925205, 0.7544855 , 0.79573263, 0.83578828, 0.94472731],
       [0.00493109, 0.02207832, 0.183718  , 0.75136821, 0.81152562],
       [0.01672657, 0.08963956, 0.14422528, 0.15459377, 0.87653561],
       [0.12526062, 0.16106085, 0.18363688, 0.44559515, 0.67690566],
       [0.08073142, 0.20659362, 0.21596298, 0.42263735, 0.55872972],
       [0.06822686, 0.32182733, 0.49568447, 0.70626162, 0.83210941]])

# 선형대수 연산

In [254]:
x = np.array([[1,2,3],
            [4,5,6]])

In [255]:
y = np.array([[6,20],[7,21],[8,22]])

In [256]:
np.dot(x,y)

array([[ 44, 128],
       [107, 317]])

In [257]:
x @ y

array([[ 44, 128],
       [107, 317]])

In [259]:
w = np.array([[2,3],[5,6]])

In [260]:
y = np.array([[4],[5]])

In [261]:
w_1 = np.linalg.inv(w)

In [262]:
np.dot(w_1,y)

array([[-3.        ],
       [ 3.33333333]])

# linalg 모듈
- 선형대수에 필요한 역행렬과 행렬식에 관한 함수를포함하고 있다.
    - det : 행렬식을 계산
    - inv : 역행렬 (정사각 행렬만 가능)
    - ---------------------------
    - eig : 고윳값 고유벡터 계산
    - qr : qr분해 계산
    - svd : 특잇값 분해 계산
    - matrix_rank : 행렬 의 rank를 반환한다.

In [264]:
np.linalg.solve(w,y)

array([[-3.        ],
       [ 3.33333333]])

In [268]:
np.linalg.matrix_rank(w) # 독립차원의 차수

2

In [267]:
np.ndim(w) #실제 차원은 아니다. tensor기준의 차원

2